#!/bin/bash
# Si il s'agit de la première exécution du script

echo -e "\nCe programme est destiné à mettre à jour votre système de manière interactive ou automatique."
echo -e "Un certain nombre de modules complémentaires peuvent être ajoutés afin d'apporter des fonctionnalités supplémentaires"

echo -ne "\n${JAUNE}Voulez-vous commencer l'installation ? (yes/no) : $RESET"; read -p "" CONFIRM &&
if [ "$CONFIRM" != "yes" ];then
    clean_exit
fi

echo -e "\n ${JAUNE}Configuration générale\n${RESET}"

echo -ne " Quel est le type de ce serveur ou de cette machine (exemple : fo, bo, bdd, PC,...) : ";read -p "" SERVER_TYPE

# Utile seulement si le module reposerver est activé :
echo -ne " Indiquez l'environnement de ce serveur (par defaut : prod) : ";read -p "" SERVER_ENV
if [ -z "$SERVER_ENV" ];then SERVER_ENV="prod";fi # Si laissé vide, on met la valeur par défaut (prod)

echo -ne " Indiquez les paquets à exclure en cas de mise à jour majeure (laisser vide si N/A) : ";read -p "" CONF_SOFT_EXCLUDE_MAJOR
echo -ne " Indiquez les paquets à exclure dans tous les cas (laisser vide si N/A) : ";read -p "" CONF_SOFT_EXCLUDE
echo -ne " Indiquez les paquets nécessitant un redémarrage de service si mis à jour (laisser vide si N/A) : ";read -p "" CONF_SOFT_NEED_RESTART
echo -ne " Autoriser la mise à jour automatique de ce script à chaque exécution (yes/no) : ";read -p "" ALLOW_SELF_UPDATE
echo -ne " Recevoir les rapports de mise à jour et d'erreurs par mail (yes/no) : ";read -p "" CONFIRM
if [ "$CONFIRM" == "yes" ];then 
	echo -ne " Sur quelle adresse mail envoyer les rapports ? : ";read -p "" MAIL_DEST
fi
# Dernières vérifs avant d'intégrer le tout dans le fichier de conf, on vérifie que toutes les variables sont renseignées (non-vide) :
# Revoir les messages d'erreurs
if [ -z "$OS_FAMILY" ];then   echo -e "[$JAUNE ERREUR $RESET] OS non reconnu";clean_exit;fi
if [ -z "$PKG_MANAGER" ];then echo -e "[$JAUNE ERREUR $RESET] Gestionnaire de paquets non reconnu";clean_exit;fi
if [ -z "$SERVER_TYPE" ];then echo -e "[$JAUNE ERREUR $RESET] Type de serveur non renseigné";clean_exit;fi
if [ -z "$ALLOW_SELF_UPDATE" ];then echo -e "[$JAUNE ERREUR $RESET] Mise à jour automatique du script non renseigné";clean_exit;fi

echo -ne "\nGénération du fichier de conf : "
echo -e "# Fichier de conf de linuxautoupdate pour $HOSTNAME" > $CONF
echo "[CONFIGURATION]" >> $CONF
echo "TYPE=\"$SERVER_TYPE\"" >> $CONF
echo "ENV=\"$SERVER_ENV\"" >> $CONF
echo "MAIL_DEST=\"$MAIL_DEST\"" >> $CONF
echo "ALLOW_SELF_UPDATE=\"$ALLOW_SELF_UPDATE\"" >> $CONF
echo -e "\n[SOFTWARE CONFIGURATION]" >> $CONF
echo "EXCLUDE_MAJOR=\"$CONF_SOFT_EXCLUDE_MAJOR\"" >> $CONF
echo "EXCLUDE=\"$CONF_SOFT_EXCLUDE\"" >> $CONF
echo "NEED_RESTART=\"$CONF_SOFT_NEED_RESTART\"" >> $CONF
echo "KEEP_CRON=\"no\"" >> $CONF
echo -e "[$VERT OK $RESET]\n"

# Affichage des modules disponibles à l'installation
getModules

echo -ne "Exécuter linuxautoupdate ? (yes/no) : ";read -p "" CONFIRM
if [ "$CONFIRM" != "yes" ];then
	clean_exit
fi


# + ajouter un raccourci dans bash_aliases pour appeler ce script