#!/bin/bash

echo -e "Configuration automatique de linuxautoupdate et des fichiers .repo"
while [ -z "$SERVER_TYPE" ];do
	read -p " → Type de serveur, laissez vide pour afficher tous les types disponibles : " SERVER_TYPE
	if [ -z "$SERVER_TYPE" ];then # Si laissé vide, on affiche tous les types disponibles, pour cela on télécharge tous les types depuis le serveur de repo
		echo -e "$JAUNE"
		# On recupère tous les types qui sont entre crochets depuis le serveur de repos, et on retire tous les crochets pour les afficher plus clairement : 
		curl -s "https://URL-reposerver/linuxautoupdate.allconf" | grep "\[.*\]" | sed 's|\]\[|\n|g' | sed 's|\[||g' | sed 's|\]| |g'
		echo -e "$RESET"
	fi
done
while [ -z "$SERVER_ENV" ];do
	read -p " → Environnement : " SERVER_ENV
done

mkdir -p /root/scripts/linuxautoupdate/ &&
cd /root/scripts/linuxautoupdate/ &&
echo -e "# Fichier de conf de linuxautoupdate pour le serveur $HOSTNAME\n[CONF]\nTYPE=\"$SERVER_TYPE\"\nENV=\"$SERVER_ENV\"\n[SOFT]\nALLOW_OVERWRITE=\"yes\"\nALLOW_REPOSFILES_OVERWRITE=\"yes\"" > linuxautoupdate.conf # Injection de la conf de base pour linuxautoupdate.conf
chmod 600 linuxautoupdate.conf 
echo -e "\n${VERT}Configuration terminée${RESET}\n"

# La conf de base ayant été injectée, tout le reste de la conf sera récupérée à la première exécution du script par les fonctions check_version et update_repos_conf