#!/bin/bash

# Nettoyage et fin du script
# Mettre ici tous les fichiers ou répertoires à nettoyer avant l'arrêt du script

# Nettoyage des fichiers temporaires
rm "/opt/linuxautoupdate.maj.sh" -f
rm "/opt/reposconf/" -rf
rm "$LOG_RAPPORT_MAIL" -f
rm "/tmp/linuxautoupdate" -rf

if [ "$MOD_ERROR" -gt "0" ];then
	sendMail
fi

exit