#!/bin/bash
# Script de première installation des fichiers de linuxautoupdate
# Permet de mettre en place les fichiers de configuration au bon endroit (copie dans /etc/...)
# La configuration de linuxautoupdate.conf est effectuée par linuxautoupdate lui-même lors de sa première exécution

# Si ce script est exécuté, c'est que l'archive a été extraite, on peut donc copier les fichiers au bon endroit

set -u
# Variables de couleurs :
BLANC=$(tput setaf 7)
GRIS=$(tput setaf 8)
VERT=$(tput setaf 2)
ROUGE=$(tput setaf 1)
JAUNE=$(tput setaf 3)
CYAN=$(tput setaf 6)
RESET=$(tput sgr0)
PWD=$(pwd)
BASE_DIR=""
CONFIRM=""
ASSUMEYES="0"
# Si on passe le paramètre --yes au script alors on utilise tous les paramètres par défaut et on répond 'y' à toutes les questions ci-dessous
while [ $# -ge 1 ];do 
    case "$1" in 
        --yes|-y)
        ASSUMEYES="1"
        ;;
    esac
	shift
done


## Répertoire d'installation de linuxautoupdate
echo -e "\nRépertoire d'installation de linuxautoupdate (par défaut /opt/linuxautoupdate/)"
if [ "$ASSUMEYES" == "0" ];then
    echo -n "Laissez vide pour utiliser le répertoire par défaut, sinon précisez le nouvel emplacement : "; read -p "" BASE_DIR
fi
if [ -z "$BASE_DIR" ];then
    BASE_DIR="/opt/linuxautoupdate"
fi
if [ -d "$BASE_DIR" ];then
    if [ "$ASSUMEYES" == "0" ];then
        echo -n "Le répertoire $BASE_DIR existe déjà, son contenu sera écrasé. Confirmez (y/n) : "; read -p "" CONFIRM
        if [ "$CONFIRM" != "y" ];then
            exit
        fi
    fi
    # On supprime le contenu du répertoire
    rm "$BASE_DIR" -rf
fi
# Si le répertoire n'existe pas, on le crée
if [ ! -d "$BASE_DIR" ];then
    mkdir -p "$BASE_DIR"
fi

# Création des répertoires de linuxautoupdate dans /etc/
mkdir -p /etc/linuxautoupdate/vars/

# Copie des fichiers de configuration
cp "${PWD}/vars/main.vars" /etc/linuxautoupdate/vars/main.vars
cp "${PWD}/vars/customs.vars" /etc/linuxautoupdate/vars/customs.vars
echo -e "\nBASE_DIR=\"${BASE_DIR}\"" >> /etc/linuxautoupdate/vars/customs.vars

# Copie des fichiers de linuxautoupdate (fonctions bash)
cp -r ${PWD}/functions ${BASE_DIR}/

# Copie du fichier de version actuelle
cp version ${BASE_DIR}/

# Copie puis création d'un lien symbolique vers le programme principal
cp ${PWD}/linuxautoupdate ${BASE_DIR}/linuxautoupdate

echo "Un lien symbolique pointant vers linuxautoupdate va être créé dans /usr/bin/"
echo -n "linuxautoupdate sera alors exécutable depuis la commande 'linuxautoupdate'. Continuer ? (y/n) : "; read -p "" CONFIRM
if [ "$CONFIRM" == "y" ];then
    rm /usr/bin/linuxautoupdate -f
    ln -s ${BASE_DIR}/linuxautoupdate /usr/bin/linuxautoupdate
    chmod 700 ${BASE_DIR}/linuxautoupdate
fi

echo -n "Installation terminée. Exécuter linuxautoupdate ? (y/n) : "; read -p "" CONFIRM
if [ "$CONFIRM" == "y" ];then
    # Exécution de linuxautoupdate (depuis $BASE_DIR au cas où le lien symbolique n'a pas été créé précédemment)
    exec ${BASE_DIR}/linuxautoupdate
else
    exit
fi